name: Publish
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    permissions:
      id-token: write  # required for trusted publishing
    environment: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get python versions
        uses: chris48s/satisfying-python@main
        id: python-versions

      - name: Build, Test, Lint
        uses: chris48s/python-package-shared@main
        with:
          python-version: '${{ steps.python-versions.outputs.min }}'
          pre-install: poetry

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
